<table class="table">
   <tr>
       <th>userTitle</th>
       <th>userContent</th>
       <th><a>Add/Del users</a></th>
   </tr>
   <?php foreach ($paginator as $users) : ?>
       <tr>
           <td><?php echo $this->escapeHtml($users->usertitle);?></td>
           <td><?php echo $this->escapeHtml($users->usercontent);?></td>
           <td>
               <a href="<?php echo $this->url('user/edit', array('action' =>'edit', 'id' => $users->userid));?>">
                  <?php echo$this->translate("Edit") ?>
               </a>
               <a href="<?php echo $this->url('user/delete', array('action' =>'delete', 'id' => $users->userid));?>">
                    <?php echo$this->translate("Delete") ?>
               </a>
           </td>
       </tr>
   <?php endforeach; ?>
</table>
