<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>注册</title>
</head>

<body>
    <h1>注册</h1>
       待实现...<br />
    <a href="/user">首页</a><br />
    <a href="/user/login">登陆</a><br />
    <a href="/user/register">注册</a>
</body>
</html>


