<?php
  $title = 'My';
  $this->headTitle($title);
?>
<table class="table">
   <caption><?php echo $this->escapeHtml($this->table); ?></caption>
   <tr>
       <th>Title</th>
       <th>Content</th>
       <th><a href="<?php echo $this->url('news', array('action' => 'add'));?>">Add news</a></th>
   </tr>
   <?php foreach ($paginator as $news) : ?>
       <tr>
           <td><?php echo $this->escapeHtml($news->title);?></td>
           <td><?php echo $this->escapeHtml($news->content);?></td>
           <td>
               <a href="<?php echo $this->url('news', array('action' =>'edit', 'id' => (string)$news->id));?>">
                  <?php echo $this->translate("Edit") ?>
               </a>
               <a href="<?php echo $this->url('news', array('action' =>'delete', 'id' => (string)$news->id));?>">
                  <?php echo $this->translate("Delete") ?>
               </a>
           </td>
       </tr>
   <?php endforeach; ?>
</table>
<?php
     echo $this->paginationControl($this->paginator,'sliding',
                                     array('news/index/paginator.phtml','News'),
                                     array('route'=>'news','action'=>'list'));
?>
